# Generated by Django 4.2.6 on 2023-12-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=62, verbose_name='タイトル')),
                ('slug', models.SlugField(verbose_name='URLスラッグ（英語）')),
                ('image', models.ImageField(blank=True, help_text='登録しない場合は、デフォルトのイメージ写真を使用する', upload_to='article_image', verbose_name='記事のイメージ写真')),
                ('body', models.TextField(verbose_name='本文')),
                ('status', models.PositiveSmallIntegerField(default=1, help_text='1:下書き, 2:公開', verbose_name='公開ステータス')),
                ('liked', models.IntegerField(default=0, verbose_name='いいね数')),
                ('categories', models.ManyToManyField(to='textbooks.textbookcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name_plural': '教科書',
            },
        ),
    ]
