# Generated by Django 4.2.6 on 2023-12-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='単語カテゴリ')),
            ],
            options={
                'verbose_name_plural': '単語カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=62, verbose_name='単語')),
                ('answer', models.CharField(max_length=62, verbose_name='答え')),
                ('explanation', models.TextField(verbose_name='解説')),
                ('categories', models.ManyToManyField(to='wordquiz.wordcategory', verbose_name='単語カテゴリ')),
            ],
            options={
                'verbose_name': '問題',
                'verbose_name_plural': '問題セット',
            },
        ),
    ]
